# Dockerfile.kafka-consumer
FROM python:3.9

WORKDIR /app

# Install dependencies
RUN pip install kafka-python minio

# Copy service
COPY scripts/ingestion/kafka_fashion_consumer.py ./kafka_fashion_consumer.py

# Run service
CMD ["python", "kafka_fashion_consumer.py"]