# Dockerfile.kafka-producer
FROM python:3.9 

WORKDIR /app

# Install dependencies
RUN pip install psycopg2-binary kafka-python

# Copy service
COPY scripts/ingestion/kafka_fashion_producer.py .

# Run service
CMD ["python", "kafka_fashion_producer.py"]