FROM python:3.9

WORKDIR /app

# Install with JSON support
RUN pip install psycopg2-binary faker psycopg2[binary]

COPY scripts/producer/api_data_generator.py ./api_data_generator.py

CMD ["python", "api_data_generator.py"]