FROM bitnami/spark:3.5.0

USER 1001

# Copy your script
COPY bronze_to_silver_all_sources.py /opt/spark-apps/

# Run the streaming job (PostgreSQL jar already mounted)
CMD ["spark-submit", \
     "--master", "spark://spark-master:7077", \
     "--jars", "/opt/spark/jars/extra/postgresql-42.6.0.jar", \
     "/opt/spark-apps/bronze_to_silver_all_sources.py"]